### PR TITLE
Update to latest cg-style

### PR DESCRIPTION
**Pull request by msecret**

### CODE REVIEW

**Comment by afeld** [comment]
I may have brought this up before, but maybe we should merge this with the https://github.com/18F/cg-style repository?

The change looks fine, but I'll let you or @jeremiak merge.

**Comment by jeremiak** [comment]
Following on @afeld's point: what is the rationale for having two distinct repos? It seems like this makes it a bit more complicated to build, but easier to publish to Ruby Gems since it just contains compiled assets?

Also, @msecret is it correct to assume that this version number bump goes along with 761630be9129ba1ccc7d9ca7dbbf444448ed99a4?

**Comment by msecret** [comment]
I think I followed what WDS was doing, but we could potentially keep it all in the `cg-style` repo and publish the ruby gem from there.

We should figure out a pattern for this that would work for other 18F projects like WDS.

**Comment by jeremiak** [comment]
@msecret I'm fine with publishing it from the same repo as long as it pretty clear. I actually don't think its that hard to manage these two things because of the `npm run gem` scripts in `cg-style` but I'm open to whatever.

Is there a good project to look at to understand how we would publish the gem from 18f/cg-style?

**Pull request closed without merging**
